change readme, repo structure and add kubernetes example
cefriel/chimera-deployment-templates pull request #1
Opened 2024-03-22 09:24 UTC by AuPath

- Changed repo structure
- Added kubernetes example, removed the 'metrics' component as it is not relevant
- Slimmed down the main README file

2024-03-22 13:50 UTC, marioscrock requested changes

2024-03-22 13:50 UTC, marioscrock commented on Kubernetes/camel-context.xml
Remove this file

2024-03-22 13:50 UTC, marioscrock commented on README.md
Specify that the Dockerfiles provided should be modified to be executed considering a Chimera project

2024-03-22 13:50 UTC, marioscrock commented on Kubernetes/Dockerfile
Change also this one to be generic and not related to "chimera-tutorial.jar"

2024-03-22 13:50 UTC, marioscrock commented on Kubernetes/README.md
Change to be generic (e.g., remove mention to cefriel/chimera:tutorial-advanced) and perform a check with a different project to see if it works.

2024-03-22 13:50 UTC, marioscrock commented on Kubernetes/chimera-converter.yml
Change it to be generic not bound to chimera-tutorial-advanced

2024-03-22 17:28 UTC, marioscrock commented on README.md
Maybe we can add something from the README prepared by Gianluca. At least briefly explain the artifacts in each folder. Alternatively we can split it in 3 and put three README in the 3 folders.

2024-03-27 09:03 UTC, AuPath commented on README.md
I added a readme to each deployment option

2024-03-27 17:22 UTC, marioscrock commented on Kubernetes/chimera-converter.yml
Add also example file initialised to execute chimera-minimal? Can be a good idea also to make "runnable" the other deployment templates.

2024-03-27 17:22 UTC, marioscrock reviewed
Add also example file initialised to execute chimera-minimal? Can be a good idea also to make "runnable" the other deployment templates.

2024-03-28 11:50 UTC, merged